ag3:
      sample_sets: [
            # Ag1000G phase 3 sample sets in Ag3.0
            "AG1000G-GH", 
            'AG1000G-ML-A',
            'AG1000G-BF-A',
            'AG1000G-BF-B',
            'AG1000G-GN-A',
            'AG1000G-GN-B',
            'AG1000G-TZ',
            # GAARDIAN sample set in Ag3.4
            '1244-VO-GH-YAWSON-VMF00149',
            # GAARD Ghana sample set in Ag3.2
            "1244-VO-GH-YAWSON-VMF00051",
            '1245-VO-CI-CONSTANT-VMF00054',
            '1253-VO-TG-DJOGBENOU-VMF00052',
            '1237-VO-BJ-DJOGBENOU-VMF00050']

reference: "resources/reference/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa"

LocusOfInterest:
      name: "coeae1f"
      contig: "2L"
      region: "2L:28520000-28580000"
      start: 28_520_000
      end: 28_580_000
      focus: 28_547_767


phylo:
      activate: True
      regions:
            focal: 28_547_767
            upstream: 30_547_767
            downstream: 26_547_767
            collinear: 45_000_000
      flanking: 10_000
      

mvncall:
      activate: False

      
indels:
      activate: False